server:
  port: 8001


spring:
  application:
    name: cloud-provider-hygtrix-payment


eureka:
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/



